### ISSUE TITLE
【EPOCH】ArcoCD設定のDeploy権限ユーザ選択モーダルのデザイン修正

### ISSUE THREAD

**Issue by matsumoto-epoch** [exastro-suite/epoch-docs#17]
・Deploy権限メンバーの選択で、メールアドレス列を削除
・メールアドレス列を削除したうえで、カラム列幅のバランスが変わるので修正していただきたいです。

**Comment by katokeita** [comment]
削除、調整しました。

**Comment by matsumoto-epoch** [comment]
調整ありがとうございます。
問題ありませんでしたのでクローズします。
