### ISSUE TITLE
【EPOCH】Deploy権限メンバー選択モーダルを表示した際にユーザが表示されない事象の修正

### ISSUE THREAD

**Issue by matsumoto-epoch** [exastro-suite/epoch-docs#18]
・Deploy権限メンバー選択モーダルを表示すると、setBodyHTML() 処理でエラーになる（「thd.id」がundefinedになっていて設定されていない？）ので修正をお願いします。

**Comment by katokeita** [comment]
修正しました。

**Comment by matsumoto-epoch** [comment]
修正ありがとうございます。
問題ありませんでしたのでクローズします。
