### ISSUE TITLE
【EPOCH】Exastro webページのウェビナー情報更新について

### ISSUE THREAD

**Issue by y-oka2** [exastro-suite/epoch-docs#19]
Exastro webページのEPOCHウェビナーの内容を変更いただきたい。
Ex-C10-Lv1に記載のある「EストアモデルのDevOps」
と
Ex-C10-Lv2に記載のある「特設イベントシステムモデルのDevOps」
を入れ替えていただきたいです。

**Comment by katokeita** [comment]
差し替えました。
https://exastro-suite.github.io/epoch-docs/webinar_ja.html
