### ISSUE TITLE
【EPOCH】Workspace画面の変更（変更点強調）

### ISSUE THREAD

**Issue by Eiji-Nakahashi** [exastro-suite/epoch-docs#23]
・入力項目があるダイアログ全般において、変更したらアイコンがかわって変更されたとわかる、または、変更された箇所がワークスペース作成ボタン押下時に変更点が表示されるようにしたい
★EPOCHチームとしては、実現方法も含め、お任せしたい
★変更のチェック方法は元の値と比較するのかそれともキーの入力で判断するか、お任せします
★各ダイアログの変更がありなしを判断できるフラグが欲しいです（後続で使用したい）

**Comment by matsumoto-epoch** [comment]
問題ないことを確認したのでクローズします。
