### ISSUE TITLE
【EPOCH】Workspace画面の変更（CD実行ボタンの強調）

### ISSUE THREAD

**Issue by Eiji-Nakahashi** [exastro-suite/epoch-docs#25]
・カーソルあてた時に動きがあった方が分かり易い
・CD実行ボタンに関してはサイズも大きくした方が良い
・他のリンクボタンも同様
★ボタンとわかりやすいようにしてもらえればと思います

**Comment by matsumoto-epoch** [comment]
問題ないことを確認したのでクローズします。
