### ISSUE TITLE
【EPOCH】英語翻訳対応

### ISSUE THREAD

**Issue by matsumoto-epoch** [exastro-suite/epoch-docs#51]
EPOCHの翻訳をお願い致します。

**Comment by matsumoto-epoch** [comment]
翻訳元は以下のExcel資料になります。
資料の各シートのテキスト列を、翻訳していただきたいです。

[多言語管理表_JA.xls](https://github.com/exastro-suite/epoch-docs/files/8000580/_JA.xls)

**Comment by matsumoto-epoch** [comment]
また、翻訳後の文言は以下の資料にまとめていただけると助かります。
先ほど送付した資料と同じ構成になっているため、対応するIDに翻訳した文言を埋めていただければと思います。

[多言語管理表_EN.xlsx](https://github.com/exastro-suite/epoch-docs/files/8000639/_EN.xlsx)

**Comment by JoachimLarsen** [comment]
かしこまりました。対応いたします。
どうぞよろしくお願いいたします。

**Comment by JoachimLarsen** [comment]
大変お待たせしております。
以上の翻訳完成できました。以下のファイルでまとめさせていただきました。
どうぞご確認ください。また何かありましたら連絡をください。
以上、どうぞよろしくお願いいたします。

[多言語管理表_EN.xlsx](https://github.com/exastro-suite/epoch-docs/files/8130565/_EN.xlsx)

**Comment by k-matsumoto0813** [comment]
ご対応ありがとうございます。
内容を確認し、問題ありませんでした。
また、何かありましたらご依頼するかと思いますが、その際はよろしくお願いいたします。

こちらのIssueはクローズします。

**Comment by matsumoto-epoch** [comment]
ご対応ありがとうございます。
内容を確認し、問題ありませんでした。
また、何かありましたらご依頼するかと思いますが、その際はよろしくお願いいたします。

こちらのIssueはクローズします。
